spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/projdb
    username: root
    password: Cristiano$
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect


