#database configuration:MySql
spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/projdb
    username:
      root
    password:
      Cristiano$
    driver-class-name:
      com.mysql.cj.jdbc.Driver



